spring.application.name=meet_now
upload.dir=uploads
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.http.converter.json=DEBUG
spring.datasource.url=jdbc:postgresql://localhost:5432/mnd
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:database/initDb.sql
spring.jpa.hibernate.ddl-auto=none

# Дополнительные рекомендуемые настройки для Hibernate 6+
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false