spring.application.name=meet_now
server.port=8080
server.ssl.enabled=false
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.http.converter.json=DEBUG
spring.datasource.url=jdbc:postgresql://localhost:5432/mnd-test
spring.datasource.username=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:database/initDb.sql
spring.jpa.hibernate.ddl-auto=update

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false