// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:meet_now_app/server/model/interes/interest.dart';
import 'package:meet_now_app/server/model/purpose/purpose.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(InterestAdapter());
    registerAdapter(PurposeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(InterestAdapter());
    registerAdapter(PurposeAdapter());
  }
}
